server:
  port: 8200

spring:
  application:
    name: feichai-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.223.25/feichai?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: yuanjing

mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka.com:8000/eureka,http://eureka1.com:8001/eureka/