server:
  port: 8206

spring:
  application:
    name: feichai-orderGateway-service

mybatis:
  mapper-locations: classpath:mapper/*.xml


#eureka:
#  instance:
#    hostname: localhost
#    instance-id: feichai-payment-service8100
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka.com:8000/eureka,http://eureka1.com:8001/eureka/